name: Lint and Unit Test

on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - '.golangci.yml'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    paths:
      - '**.go'
      - '.golangci.yml'
      - 'go.mod'
      - 'go.sum'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-mod-
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
          cache: true
      - name: Go Mod Vendor
        run: |
          go env -w GOPRIVATE="github.com/bfi-finance/*"
          git config --global url."https://${{ secrets.GH_BRAVO_USERNAME }}:${{ secrets.GH_PAT }}@github.com".insteadOf "https://github.com"
          go version
          go mod vendor
      - name: Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
      - name: Unit Test
        run: |
          go version
          make test
      # TODO: send sonarqube here